LAMP1_SENSOR_PIN = 9
LAMP2_SENSOR_PIN = 10
LAMP3_SENSOR_PIN = 11

LAMP1_BUTTON_PIN = 16
LAMP2_BUTTON_PIN = 20
LAMP3_BUTTON_PIN = 21

LAMP_BUTTON_HOLD_TIME = 3

DATABASE_NAME = 'recuperator.db.json'

BUZZER_PIN = 23

DISPLAY_UPDATE_TIME = 5

LOG_FILENAME = 'recuperator.log'